podTemplate(yaml: '''
    apiVersion: v1
    kind: Pod
    spec:
      containers:
      - name: centos
        image: centos
        command:
        - sleep
        args:
        - 99d
      restartPolicy: Never
''') {
 node(POD_LABEL) {
   stage('k8s') {
     git 'https://github.com/judenm/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git'
               container('centos') {
                 stage('start calculator') {
                   sh '''
                   dnf --disablerepo '*' --enablerepo=extras swap centos-linux-repos centos-stream-repos -y
                   dnf distro-sync -y
                   yum -y install bind-utils
                   cd Chapter08/sample1
                   curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
                   chmod +x ./kubectl
                   ./kubectl apply -f calculator.yaml -n staging
                   ./kubectl apply -f hazelcast.yaml -n staging
                   sleep 30
                   ./kubectl get pods -w -n staging
                   test $(curl -i calculator-service.staging.svc.cluster.local:8080/sum?a=3\\&b=4) -eq 7 && echo 'pass' || 'fail'
                   '''
               }
            }
        }
    }
}
